service: cloudwatch-ec2-sg

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeSecurityGroups"
      Resource: "*"
  environment: 
    SLACK_URL: "<your-slack-webhook>"

functions:
  panopticon:
    handler: handler.panopticon
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "AWS API Call via CloudTrail"
            detail:
                eventSource:
                    - "ec2.amazonaws.com"
                eventName:
                    - "CreateSecurityGroup"
                    - "DeleteSecurityGroup"
                    - "RevokeSecurityGroupIngress"
                    - "RevokeSecurityGroupEgress"
                    - "AuthorizesecuritygroupIngress"
                    - "AuthorizesecuritygroupEgress"
